const sampleListing = [
    {
        place: "Goa Beach Hut",
        title: "Beachside Wooden Hut",
        description:
            "Minimal beach hut with direct sea access and sunsets that slap.",
        price: 1200,
        location: "Goa",
        country: "India",
        Query: 2,
        email: "host1@example.com",
        image: {
            filename: "beach",
            url: "../Models/img.jpg",
        },
    },
    {
        place: "Manali Cabin",
        title: "Himalayan Wooden Cabin",
        description: "Cold nights, hot chai, zero city noise.",
        price: 1500,
        location: "Manali",
        country: "India",
        Query: 3,
        email: "host2@example.com",
        image: {
            filename: "mountain",
            url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&fit=crop",
        },
    },
    {
        place: "Jaipur Haveli",
        title: "Royal Pink City Haveli",
        description: "Traditional Rajasthani architecture with modern comfort.",
        price: 2000,
        location: "Jaipur",
        country: "India",
        Query: 4,
        email: "host3@example.com",
        image: {
            filename: "heritage",
            url: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&fit=crop",
        },
    },
    {
        place: "Kerala Backwaters",
        title: "Backwater Houseboat",
        description: "Float, eat, sleep. Repeat.",
        price: 1800,
        location: "Alappuzha",
        country: "India",
        Query: 1,
        email: "host4@example.com",
        image: {
            filename: "houseboat",
            url: "https://images.unsplash.com/photo-1600508774634-4e11d34730e2?w=800&fit=crop",
        },
    },
    {
        place: "Ladakh Camp",
        title: "High Altitude Tent Stay",
        description: "Stars, silence, and oxygen scarcity.",
        price: 1000,
        location: "Leh",
        country: "India",
        Query: 5,
        email: "host5@example.com",
        image: {
            filename: "camp",
            url: "https://source.unsplash.com/800x600/?mountains,tent",
        },
    },
    {
        place: "Mumbai Studio",
        title: "Compact City Studio",
        description: "Small, expensive, unbeatable location.",
        price: 2500,
        location: "Mumbai",
        country: "India",
        Query: 2,
        email: "host6@example.com",
        image: {
            filename: "city",
            url: "https://images.unsplash.com/photo-1467987506553-8f3916508521?w=800&fit=crop",
        },
    },
    {
        place: "Pondicherry Villa",
        title: "French Style Villa",
        description: "Pastel walls, bicycles, peace.",
        price: 2200,
        location: "Pondicherry",
        country: "India",
        Query: 3,
        email: "host7@example.com",
        image: {
            filename: "villa",
            url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&fit=crop",
        },
    },
    {
        place: "Ooty Cottage",
        title: "Hilltop Tea Cottage",
        description: "Misty mornings and endless tea.",
        price: 1400,
        location: "Ooty",
        country: "India",
        Query: 4,
        email: "host8@example.com",
        image: {
            filename: "cottage",
            url: "https://source.unsplash.com/800x600/?cottage,hills",
        },
    },
    {
        place: "Rishikesh Ashram",
        title: "Yoga Retreat Stay",
        description: "WiFi weak, inner peace strong.",
        price: 900,
        location: "Rishikesh",
        country: "India",
        Query: 1,
        email: "host9@example.com",
        image: {
            filename: "yoga",
            url: "https://source.unsplash.com/800x600/?yoga,river",
        },
    },
    {
        place: "Shillong Homestay",
        title: "Rainy Hill Homestay",
        description: "Clouds literally enter your room.",
        price: 1300,
        location: "Shillong",
        country: "India",
        Query: 2,
        email: "host10@example.com",
        image: {
            filename: "rain",
            url: "https://source.unsplash.com/800x600/?rain,hills",
        },
    },

    // ---- 10 more (international vibe) ----

    {
        place: "Bali Villa",
        title: "Private Pool Villa",
        description: "Instagram bait with actual comfort.",
        price: 3000,
        location: "Bali",
        country: "Indonesia",
        Query: 3,
        email: "host11@example.com",
        image: {
            filename: "bali",
            url: "https://source.unsplash.com/800x600/?bali,villa",
        },
    },
    {
        place: "Tokyo Apartment",
        title: "Minimal Tokyo Apartment",
        description: "Tiny, efficient, futuristic.",
        price: 2800,
        location: "Tokyo",
        country: "Japan",
        Query: 4,
        email: "host12@example.com",
        image: {
            filename: "tokyo",
            url: "https://source.unsplash.com/800x600/?tokyo,apartment",
        },
    },
    {
        place: "Swiss Chalet",
        title: "Alpine Wooden Chalet",
        description: "Snow, silence, perfection.",
        price: 3500,
        location: "Zermatt",
        country: "Switzerland",
        Query: 5,
        email: "host13@example.com",
        image: {
            filename: "chalet",
            url: "https://source.unsplash.com/800x600/?chalet,snow",
        },
    },
    {
        place: "NYC Loft",
        title: "Industrial City Loft",
        description: "Brick walls and city noise.",
        price: 4000,
        location: "New York",
        country: "USA",
        Query: 3,
        email: "host14@example.com",
        image: {
            filename: "loft",
            url: "https://source.unsplash.com/800x600/?loft,newyork",
        },
    },
    {
        place: "Santorini House",
        title: "White Cliffside Home",
        description: "Blue domes, white walls, sunsets.",
        price: 3200,
        location: "Santorini",
        country: "Greece",
        Query: 4,
        email: "host15@example.com",
        image: {
            filename: "santorini",
            url: "https://source.unsplash.com/800x600/?santorini,house",
        },
    },
    {
        place: "Dubai Penthouse",
        title: "Luxury Desert Penthouse",
        description: "Glass, gold, excess.",
        price: 5000,
        location: "Dubai",
        country: "UAE",
        Query: 5,
        email: "host16@example.com",
        image: {
            filename: "dubai",
            url: "https://source.unsplash.com/800x600/?dubai,penthouse",
        },
    },
    {
        place: "Iceland Cabin",
        title: "Aurora Glass Cabin",
        description: "Sleep under northern lights.",
        price: 4200,
        location: "Reykjavik",
        country: "Iceland",
        Query: 4,
        email: "host17@example.com",
        image: {
            filename: "aurora",
            url: "https://source.unsplash.com/800x600/?aurora,cabin",
        },
    },
    {
        place: "Paris Studio",
        title: "Romantic Paris Studio",
        description: "Croissants, balconies, clichés.",
        price: 2600,
        location: "Paris",
        country: "France",
        Query: 2,
        email: "host18@example.com",
        image: {
            filename: "paris",
            url: "https://source.unsplash.com/800x600/?paris,apartment",
        },
    },
    {
        place: "Amazon Lodge",
        title: "Jungle Eco Lodge",
        description: "Nature louder than thoughts.",
        price: 1700,
        location: "Amazon",
        country: "Brazil",
        Query: 5,
        email: "host19@example.com",
        image: {
            filename: "jungle",
            url: "https://source.unsplash.com/800x600/?jungle,lodge",
        },
    },
    {
        place: "Maldives Villa",
        title: "Overwater Luxury Villa",
        description: "Water below, stars above.",
        price: 6000,
        location: "Maldives",
        country: "Maldives",
        Query: 5,
        email: "host20@example.com",
        image: {
            filename: "maldives",
            url: "https://source.unsplash.com/800x600/?maldives,villa",
        },
    },
    {
        place: "Darjeeling Viewpoint Stay",
        title: "Tea Garden View Homestay",
        description: "Wake up to misty hills and endless tea estates.",
        price: 1100,
        location: "Darjeeling",
        country: "India",
        Query: 3,
        email: "host21@example.com",
        image: {
            filename: "tea",
            url: "https://source.unsplash.com/800x600/?tea,garden,hills",
        },
    },
    {
        place: "Jaisalmer Desert Camp",
        title: "Luxury Sand Dune Camp",
        description: "Golden dunes, cold nights, unreal silence.",
        price: 1600,
        location: "Jaisalmer",
        country: "India",
        Query: 4,
        email: "host22@example.com",
        image: {
            filename: "desert",
            url: "https://source.unsplash.com/800x600/?desert,camp",
        },
    },
    {
        place: "Udaipur Lake Palace Stay",
        title: "Lake Facing Heritage Stay",
        description: "Royal vibes without royal prices.",
        price: 2300,
        location: "Udaipur",
        country: "India",
        Query: 4,
        email: "host23@example.com",
        image: {
            filename: "lake",
            url: "https://source.unsplash.com/800x600/?lake,palace",
        },
    },
    {
        place: "Hampi Stone House",
        title: "Ancient Ruins Stay",
        description: "History outside, minimalism inside.",
        price: 900,
        location: "Hampi",
        country: "India",
        Query: 2,
        email: "host24@example.com",
        image: {
            filename: "ruins",
            url: "https://source.unsplash.com/800x600/?ancient,ruins",
        },
    },
    {
        place: "Coorg Coffee Estate",
        title: "Private Coffee Plantation Stay",
        description: "Smells like coffee, sounds like rain.",
        price: 1700,
        location: "Coorg",
        country: "India",
        Query: 3,
        email: "host25@example.com",
        image: {
            filename: "coffee",
            url: "https://source.unsplash.com/800x600/?coffee,plantation",
        },
    },
    {
        place: "Prague Old Town Flat",
        title: "Historic European Apartment",
        description: "Cobblestones, trams, and old-world charm.",
        price: 2800,
        location: "Prague",
        country: "Czech Republic",
        Query: 3,
        email: "host26@example.com",
        image: {
            filename: "prague",
            url: "https://source.unsplash.com/800x600/?prague,oldtown",
        },
    },
    {
        place: "Norway Fjord Cabin",
        title: "Waterfront Fjord Cabin",
        description: "Cold water, warm interiors, insane views.",
        price: 3600,
        location: "Geiranger",
        country: "Norway",
        Query: 5,
        email: "host27@example.com",
        image: {
            filename: "fjord",
            url: "https://source.unsplash.com/800x600/?fjord,cabin",
        },
    },
    {
        place: "Morocco Riad",
        title: "Traditional Medina Riad",
        description: "Courtyards, tiles, and controlled chaos.",
        price: 2100,
        location: "Marrakech",
        country: "Morocco",
        Query: 4,
        email: "host28@example.com",
        image: {
            filename: "riad",
            url: "https://source.unsplash.com/800x600/?riad,morocco",
        },
    },
    {
        place: "Sydney Harbour Apartment",
        title: "Harbour View Apartment",
        description: "City skyline meets ocean air.",
        price: 3900,
        location: "Sydney",
        country: "Australia",
        Query: 4,
        email: "host29@example.com",
        image: {
            filename: "sydney",
            url: "https://source.unsplash.com/800x600/?sydney,harbour",
        },
    },
    {
        place: "Patagonia Remote Lodge",
        title: "Extreme Wilderness Lodge",
        description: "Nowhere nearby. That’s the point.",
        price: 4500,
        location: "Patagonia",
        country: "Argentina",
        Query: 5,
        email: "host30@example.com",
        image: {
            filename: "patagonia",
            url: "https://source.unsplash.com/800x600/?patagonia,lodge",
        },
    },
];

module.exports = { data: sampleListing };
